### PR TITLE
Enhancement: Rails validations brought to the client-side 

### PR DESCRIPTION
**Pull request by SteveBenner**
#### _PREFACE_

I was invited by @jgorset to contribute to one of your cool projects, and I totally picked this one. He _did_ suggest that it might be slightly crazy, but I was already two days deep in the source code when I started giving his warning serious thought… Whereas I might whip out a Rails-only solution in a few hours, I soon realized that implementing my concept would require understanding both AngularJS, and HyperAdmin. I’m totally new to both technologies—or at least that was the case a week ago.

For better or for worse, I do this thing where if I run into a challenging problem, I become ridiculously driven about solving it. I haven’t worked in a system that blends client/server paradigms like this before, and data flow was just totally murky to me. So I read code until I grokked that shit. Then I wrote a solution using the tools I know. And I loved every minute of the process. Angular has been at the top of my to-learn list for quite a while now, and I have to say that reading HyperAdmin was a _delicious_ experience. That is some **_crazy elegant Ruby**_.

**In short, no regrets were had**.

---
### WHAT IT DO

[Why not see for yourself](https://github.com/SteveBenner/hyper-admin-app-demo)
### HOW IT DO

In lieu of what would normally be a very detailed Git commit log, I chose to describe this feature in [its own doc file](https://github.com/SteveBenner/hyper_admin/blob/feature/client-side-validations/doc/Validations.md). This was also to reduce the amount of comments in source code files.
### WHY IT DO

I think any solution in a mixed-paradigm system such as this one will be be opinionated. There are so many factors involved in evaluating trade-offs that it really falls down to the individual programmers. Perhaps this is a totally FAIL solution for you, and would never work as a part of HyperAdmin. That would be OK with me, because **my point here is to show how much I love writing quality code and solving complex problems.**

### CODE REVIEW

**Comment by jgorset** [comment]
Hey thanks, @SteveBenner! This kicks ass! We really like your approach, but we can't seem to get the error messages to show up. The field displays red and the submit button is disabled and everything, but no messages appear. Are you able to reproduce this on your end, or are we doing something really silly?

screen shot 2015-05-21 at 13 32 46

```
<ng-messages for="form[attr.key].$error" class="ng-inactive">
  <!-- ngMessage: undefined -->
</ng-messages>
```

**Comment by SteveBenner** [comment]
Just saw your comment; I’m glad to hear you like it! I have considered that based on the wording of #2, @sindrenm (and anyone else on this project) likely envisioned a solution which provides validation data (such as error messages) from the context of JavaScript, particularly AngularJS. I definitely agree that my solution kicks ass, but it also certainly reveals my lack of experience with Angular.

I mentioned that I’m new to the framework… As of yet, I have not investigated the form capabilities in-depth, and I was actually a bit unsure of how the implementation should appear/function. The ERB produces the same HTML elements as original form templates contained, but that is as far as my experience with Angular took me. You can verify that the same output is there, at least, by inspecting the raw content of relevant HTML pages as they load (I use Chrome’s web dev console). For example, within `new.html` under route `/admin/articles/new` the first template (for the blog post title) contains the following error message within the `ng-messages` element:

``` html
<ng-message when="{{attr.type}}">Must have a title.</ng-message>
```

It doesn’t produce a nice shiny UI feature for me either, so this is the point where I will have to go learn more about how Angular works, haha! I’ll look into it over the weekend. I was just waiting to hear any feedback, and for a truly ideal solution I definitely think it will be an evolving process determining the best way to mix and match Ruby with AngularJS. Clearly, knowledge of Angular would be a priority for me moving forward, and that is something I plan for myself anyway.

**Comment by jgorset** [comment]
Please! @sindrenm and I took a stab at it ourselves and I think we got about halfway there. I don't want to spoil anything, but suffice to say that you're definitely on the right track. If you're up to it we'd certainly love to see how you'd tackle it.

**Comment by jgorset** [comment]
Also, are you regretting that you picked this task yet? ;-)

**Comment by SteveBenner** [comment]
**I’m on it!** This is actually the first chance I’ve had to check on GitHub this week... I ended up visiting family over the holiday weekend and just got back on Tuesday. If you’re wondering, it’s a stupid American thing (Memorial Day) that occurs every last monday of May. I normally just spend it on my computer, but it was good to see the relatives.

No regrets about taking on the project—I’m just sorry to be jumping in so late this week! I’ll post an update soon, and if I have any questions I’ll drop them here.

**Comment by jgorset** [comment]
Please do, and no rush! Oh, and if it's any consolation, vikings have their fair share of silly holidays, too.

**Comment by SteveBenner** [comment]
~~I’m starting on the code now and I wanted to ask if you’d prefer a solution utilizing the `ngMessages` directive as suggested by the initial HTML, or the more basic technique of using `ngShow` with appropriate logic to present the error messages?~~

~~If it were my own project, I would use `ngMessages` because it seems more elegant. I noticed `ngShow` was prevalent in all the examples and docs for Angular forms I encountered, and it is more simple, which can be a desirable quality. If I don’t hear back soon or you don’t care which I choose,~~ **I’ll start on implementing with `ngMessages`** but I wouldn't mind switching to using `ngShow` if that’s preferred; it seems a common directive that would be good to practice.

**Edit:** Sorry this is so late on a Norwegian Monday! It was another crazy weekend, but I’ll be online and on GitHub nearly 24/7 this week :smiley:

**Comment by jgorset** [comment]
I like `ngMessages`, too. What do you think, @sindrenm? Also don't worry about it, @SteveBenner; you have all the time you need. ;-)

**Comment by sindrenm** [comment]
Any particular reason why you'd want to use `ngShow` directly instead of going through the `ngMessages` interface, @SteveBenner? `ngMessages` is designed specifically for displaying error messages in forms, and in a way acts as a `switch..case`/`case..when` for Angular, with optional `break`s. In the case of our Material design, we only want to display one error message per form field at a time, which at first thought I think could prove a bit troublesome using `ngShow`. `ngMessages` handles this by design. :smiley:

**Comment by SteveBenner** [comment]
Haha noooo, let’s **scrap** that concept. It was only a few minutes after posting my original message that I scratched it out with an edit, but I’m not the kind of person to redact my words to make myself look better :grin: by this point I’ve gone over enough material to realize `ngMessages` is what should be used.

Your mention of cardinality on the messages actually came perfectly in time… I was _just_ about to ask you here whether you wanted to use the `multiple` attribute and present all potential errors at once, or just one at a time. From a UX point of view I inherently would choose the latter, for the same reason mentioned in Angular's docs when they talk about highlighting _after_ blur… Less overwhelming is always better.

**Comment by SteveBenner** [comment]
I wouldn’t call this final, but I was much too excited not to push this update out! It fixes the validation messages, and by fix, I mean implements… After my first submission, I had stopped coding to await your response, not even realizing that AngularJS had these built-in messages. I should have asked more questions initially! So with humility, I’m still not sure this is the full picture of what you have in mind for the validation feature, but I’d love to hear your thoughts. I’ve got to say, there is some pretty sexy Ruby code in there.

After diving into Angular, it was only a few minutes before I realized the awkward gaping hole in the solution, and I realized it meant incorporating another significant data element (Angular's validation directive names for `ngMessages`). It took me a little while deciding how best to fit that in, but it was a lot of fun revising the code. Plenty of ways came to mind as I pictured the data flow (like writing two separate helpers for translation, etc etc) but in the end I kind of just focused on clarity and expressiveness with my method/identifier names.

~ Oh, and I also updated [the README of my demo app](https://github.com/SteveBenner/hyper-admin-app-demo), as I noticed the instructions were lacking...

validated-1
validated-2
validated-3

**Comment by sindrenm** [comment]
This is really great stuff, @SteveBenner! :+1:

**Comment by SteveBenner** [comment]
@jgorset Haha… Well truth be told, I’m still pretty new to using git hooks and haven’t invested enough time to make it as **shiny** as I’d like… But I find running [this hook](https://github.com/SteveBenner/git-hooks/blob/master/post-commit/convert-indentation.rb) as a `post-commit` makes my life **_way**_ easier as I am OCD about things like having ~~proper~~ consistent indentation in ALL my public code. Why not use spaces in the first place? It’s because I RubyMine for all things, and it has this feature called ‘[smart tabs](https://www.jetbrains.com/ruby/help/code-style-ruby.html#d902705e133)’ which makes editing code better, and supposedly replaces the tabs you use with spaces behind the scenes. **Except I found out that sometimes it doesn't**. So I turned to git hooks. Although it’s not perfect, it works pretty well for now :grinning:

@sindrenm I don’t think you read anything wrong, but as mentioned in my ‘line note’ response, the documentation is incomplete and/or my technique possibly overly complex (though I find it elegant). I’m actually traveling at the moment and put off updating the docs and explaining things more. Doing that soon.

I’m also wrapping up something unrelated for @jgorset as you guys are hopping on GitHub again, so bear with me as I turn towards this again, with emphasis on documenting more :smile:

**Comment by SteveBenner** [comment]
I updated [the docs](https://github.com/SteveBenner/hyper_admin/blob/feature/client-side-validations/doc/Validations.md#example) to more thoroughly explain the data flow in my solution, because I feel not doing so would necessitate more comments in the source code. It is a bit of a process, after all. Since describing it to @sindrenm resulted in such a fat comment, this indicated more documentation was a good idea.

In fact, after thinking about the comment by @sindrenm earlier, I decided to do a small refactor in the data structure and helper methods of `HyperAdmin::ValidationHelper` and I think this resulted in a much cleaner solution. I’d love to know your thoughts on this.

There are still no tests included, but I think that is the only thing missing at this point (and to squash the commits :smile:). It will have to wait until I have more time, as I’ll be tied up for the rest of June it looks like.

**Comment by jgorset** [comment]
Do you wanna merge this, @sindrenm, or should we leave it open pending that someone writes specs to go with it?

**Comment by sindrenm** [comment]
Hi guys. Sorry about not responding before now, but I've been on away for the summer and haven't really been anywhere nearby my computer for most of the time. Now that I'm back, however, I'd be really happy to merge this stuff. Even though it does't include any tests, we have seen it working, and we love the way you've been able to solve this very tricky problem. Our hats off to you, sir. :tophat: 

A small note: When squashing your commits, I know that I personally would prefer a commit message consisting of a short summary, and then perhaps a longer description following that underneath it, following this template from https://git-scm.com/book/ch5-2.html:

```
Short (50 chars or less) summary of changes

More detailed explanatory text, if necessary.  Wrap it to
about 72 characters or so.  In some contexts, the first
line is treated as the subject of an email and the rest of
the text as the body.  The blank line separating the
summary from the body is critical (unless you omit the body
entirely); tools like rebase can get confused if you run
the two together.

Further paragraphs come after blank lines.

  - Bullet points are okay, too

  - Typically a hyphen or asterisk is used for the bullet,
    preceded by a single space, with blank lines in
    between, but conventions vary here
```

**Comment by sindrenm** [comment]
Another thing to keep in mind: after merging, we should probably fixup any hyperlinks from the documentation that link directly to your repository and feature branch, as this branch will be removed and you might not want to keep your repository up any longer than you need to. :smiley:

**Comment by sindrenm** [comment]
This has waited long enough. Merging!

**Pull request merged**
